export enum TicketStatus {
  OPEN = "OPEN",
  VALIDATED = "VALIDATED",
  PROOF_CHECKED = "PROOF_CHECKED",
  AUTO_RESOLVING = "AUTO_RESOLVING",
  WAITING_FOR_USER = "WAITING_FOR_USER",
  ESCALATED = "ESCALATED",
  RESOLVED = "RESOLVED",
}
